---

- name: Remove the default site from nginx
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: Remove the default site from nginx
  file: path=/etc/nginx/sites-enabled/site state=absent

- name: Copy nginx configuration to the sites-available folder
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/{{ site_name }}

- name: Link nginx configuration to the sites-enabled folder
  file: src=/etc/nginx/sites-available/{{ site_name }} dest=/etc/nginx/sites-enabled/{{ site_name }} state=link
  notify: restart nginx

- name: Create Wordpress database
  mysql_db: name={{ wp_db_name }} state=present

- name: Create Wordpress database user
  mysql_user: name={{ wp_db_user }} password={{ wp_db_password }} priv={{ wp_db_name }}.*:ALL host='localhost' state=present

- name: Add group "deploy"
  group: name=deploy

- name: Add user "deploy"
  user: name=deploy group=deploy home=/usr/share/nginx/{{ site_name }}/

- name: Fetch random salts for Wordpress config
  local_action: command curl https://api.wordpress.org/secret-key/1.1/salt/
  register: "wp_salt"
  sudo: no

- name: Copy Wordpress config file
  template: src=wp-config.php dest=/usr/share/nginx/{{ site_name }}/

- name: Change ownership of Wordpress installation
  file: path=/usr/share/nginx/{{ site_name }}/ owner=deploy group=deploy state=directory recurse=yes
